import type {
  MissionAction,
  MissionDefinition,
  MissionPhase
} from "./missionTypes";

/**
 * CyberSim AI — Mission Engine
 *
 * Pure game logic.
 *
 * This file intentionally has NO React code.
 * React can use these functions today.
 * Later, the exact same engine can consume missions generated by AI.
 */

export interface MissionProgress {
  phase: MissionPhase;
  discoveredEvidence: string[];
  completedObjectives: string[];
  completedActions: string[];
  diagnosis: string | null;
  verificationPassed: boolean;
  completed: boolean;
}

export const createInitialProgress = (): MissionProgress => ({
  phase: "briefing",
  discoveredEvidence: [],
  completedObjectives: [],
  completedActions: [],
  diagnosis: null,
  verificationPassed: false,
  completed: false
});

export function isActionAvailable(
  mission: MissionDefinition,
  action: MissionAction,
  progress: MissionProgress
): boolean {
  if (progress.completedActions.includes(action.id)) {
    return false;
  }

  return (action.requires ?? []).every((requirement) => {
    if (requirement === "correct-diagnosis") {
      return progress.diagnosis === mission.primaryDiagnosis;
    }

    return progress.completedObjectives.includes(requirement);
  });
}

export function getRequiredActions(
  mission: MissionDefinition
): MissionAction[] {
  return mission.actions.filter((action) => action.required);
}

export function canVerify(
  mission: MissionDefinition,
  progress: MissionProgress
): boolean {
  return mission.verification.some((check) =>
    check.requiresActions.every((actionId) =>
      progress.completedActions.includes(actionId)
    )
  );
}

export function canCompleteMission(
  mission: MissionDefinition,
  progress: MissionProgress
): boolean {
  return (
    progress.verificationPassed &&
    getRequiredActions(mission).every((action) =>
      progress.completedActions.includes(action.id)
    )
  );
}

/**
 * This helper maps a completed action to an objective.
 * It keeps objective logic outside the UI.
 */
export function getObjectiveForAction(
  mission: MissionDefinition,
  actionId: string
) {
  return mission.objectives.find(
    (objective) => objective.completionKey === `action-${actionId.replace("action-", "")}`
  );
}
